### ISSUE TITLE
bug(peer-exchange): js-waku <> go-waku interop 

### ISSUE THREAD

**Issue by danisharora099** [logos-messaging/logos-delivery-go#491]
peer-exchange was converted into a request-response protocol. upon the refactor of the same within js-waku, the CI with go-waku <> js-waku for that test is now failing 

go-waku 0.5.2 addressed those changes. however, the test still is failing. opening this issue to track the same.

ref:
- https://github.com/waku-org/js-waku/pull/1193

cc @richard-ramos

**Comment by richard-ramos** [comment]
Looking at the failing test in go-waku, it seems that this line:
```
await nwaku2.waitForLog("Discovered px peers via discv5", 10);
```
is causing the timeout, as this message is not logged in go-waku. Once removed this line, the test proceeds and fails since the ENR does not contain a `multiaddrs` field. In go-waku the `multiaddrs` field is only populated when the node uses `wss` and a domain name. This is described in https://github.com/waku-org/nwaku/issues/1491#issuecomment-1399803708 and https://github.com/waku-org/nwaku/issues/1492#issuecomment-1384187896

Should this test be updated to not check for a `multiaddrs` field in the ENR? or should go-waku add the `ws` address to it. As far as I understand, normal `ws` addresses containing IP addresses are not useful in the context of js-waku.

**Comment by fryorcraken** [comment]
js-waku code caters for ENR containing both `tcp` and `wss` multiaddr. This is mainly to cater for tests running in NodeJS.

Hence, the lack fo `multiaddrs` in the ENR for this tests scenario should not be a show stopper as long as `tcp4` and `ip` are set in the ENR. It looks like to me the test should be changed to cater for the fact that only TCP multiaddr are expected in NodeJS environment
